# The cargo-make makefile
# Only used in development (optional)
# See https://sagiegurari.github.io/cargo-make/ for more info

extend = [
  { path = "./target/cargo-make/git.toml" },
  { path = "./target/cargo-make/github.toml" },
  { path = "./target/cargo-make/toml.toml" },
  { path = "./target/cargo-make/cmake.toml" }
]

[env]
X_CMAKE_UNCRUSTIFY_ENABLED = { source = "${CARGO_MAKE_CI}", default_value = "true", mapping = { "true" = "false" } }

[config]
load_script = '''
#!@duckscript
# setup directory for external makefiles
mkdir ./target/cargo-make

# load the makefile from the cargo-make-tasks repository
file = set cmake
file_path = set ./target/cargo-make/${file}.toml
if not is_file ${file_path}
  content = http_client --method GET https://raw.githubusercontent.com/sagiegurari/cargo-make-tasks/master/src/${file}.toml
  writefile ${file_path} ${content}
end

# load additional generic makefiles from cargo-make repository
files = array git github toml
for file in ${files}
  file_path = set ./target/cargo-make/${file}.toml
  if not is_file ${file_path}
    content = http_client --method GET https://raw.githubusercontent.com/sagiegurari/cargo-make/master/src/lib/descriptor/makefiles/${file}.toml
    writefile ${file_path} ${content}
  end
end
release ${files}
'''

